version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm i -g lerna aws-cdk
      - lerna bootstrap
    finally:
      - lerna link
  build:
    commands:
      - lerna run build
artifacts:
  files:
    - packages
  name: artifact-name
  discard-paths: yes
  base-directory: packages/infra